// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uavilthuyclqjnxgjmwr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVhdmlsdGh1eWNscWpueGdqbXdyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3MDgzOTcsImV4cCI6MjA2NjI4NDM5N30.FsYH0fD1pCG_z1S9dgCkQ8xoiQ4boXlpc48D8k0XeZk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});